{% set name = "scamp" %}
{% set version = "2.7.8" %}

package:
  name: astromatic-{{ name }}
  version: {{ version }}

source:
  url: https://github.com/astromatic/{{ name }}/archive/v{{ version }}.tar.gz
  sha256: 60cc44a0a8d991e88fca205e278b3c16efa462ab154fe5e5e9840eb3e40f3341
  patches:
    - 0001-Search-lapacke-library.patch
    - 0002-Fix_sprintf_buffer_overflow.patch

build:
  skip: true  # [win]
  number: 0

requirements:
  build:
    - {{ compiler('c') }}
    - autoconf
    - automake
    - libtool
    - make
  host:
    - fftw
    - curl
    - liblapacke
  run:
    - fftw
    - libcurl

test:
  commands:
    - scamp -d

about:
  home: http://www.astromatic.net/software/scamp
  license: GPL-3.0
  license_file: LICENSE
  summary: A utility that computes astrometric solutions from SExtractor catalogs
  description: |
    SCAMP (Software for Calibrating AstroMetry and Photometry) is a computer
    program that computes astrometric projection parameters from source
    catalogues derived from FITS images. The computed solution is expressed
    according to the WCS standard.
  doc_url: https://scamp.readthedocs.io/
  dev_url: https://github.com/astromatic/scamp

extra:
  recipe-maintainers:
    - teake
