travis:
  secure:
    BINSTAR_TOKEN: JSTdjfIBCF71vyzfLLwze1I9WM6ngfz/3G77velXG7iZcmnLTFOkL6KHkoPtZVE0+WS9eRtWSy/Z0tSIsdhcd9ue2BaKUB1kPU5bHxU7/xdpZJpVZl+PwynKOyKOZOXGth2Ey5VDffH6h1WRfcNtAoO8/cUZ6q1Ms9TpSWnZrwSJcUkoqSxpfJcsDAaaZ+yUtSkJ1nBrF5k5H2+hrUDsO2rr2nWZrG1npLAcFLqMdGXVKZ7llo6mwApk3BI4eYM7dMKoQnRfR5+0Ku28w+l36h3HnlrDb+x+0TzRBS1jIrm+zYAKbS2+hhYmpbZlsgEoNBrSjVywmG/EbIx3fBGzVkNAbL4XmRBVWiP3X1RM3TLVUkSkMM0NqoPGAVbpgw/q6g4UWUEAWThLs/csFqXeW07gzpka5CUZz8PfvoAg40Lhqlskq6Lcz8yZG3kT2P7r0Nt8I1czaJKVrabqpu6LoO4FBdnx59TYvRdyb2ulTOOVptdkw7xDPE2SiqSIzAt89d5vyYCiTc3D8haciC2mqm3KArfSvp/PfSWLUdRstURknL6Z4ToFzgYCB+6dYapj/rZHsRt8nAhGQ7uO47UahU0tGMxyUBZ+ie6vlsVDQlKkglXb5pxvIH9J5LkjS0N+RJzg/96Ziga2GSbqDcYme6Qxxswpr+gF0H75IzUpcw0=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
